### ISSUE TITLE
Multi target support

### ISSUE THREAD

**Issue by UniquePixels** [nickolasdeluca/pino-discord-transport#3]
I am brand new to pino and so still figuring all things out.  I will have a multitarget setup where logs are sent to file, and certain ones to Discord.

From what I can tell this transport is not following the standard transport setup and so can not work in this setup.  Is this correct?  If not how do you integrate?

**Comment by nickolasdeluca** [comment]
To be honest, I didn't use multi-targeting in my projects; it was either Discord or Slack for production or the console for debugging purposes. If you manage to figure out why it doesn't work and want to fix it, feel free to do so. Otherwise, please note that this wasn't developed with multi-targeting in mind.

**Comment by UniquePixels** [comment]
No problem, thank you for the response!  I will see if I can figure some stuff out.  If not I will go a different way.  No biggy, just did not want to spend time if someone knew something I did not!

**Comment by nickolasdeluca** [comment]
Alright, I'll close this issue and if you have any contribuitions you'd like to add, open up a pr and I'll gladly look into it.
